#!/usr/bin/env python3
"""
Replace common non-ASCII characters with ASCII equivalents.
Useful for cleaning up text generated by LLMs.
"""

import re
import sys
from pathlib import Path

# Mapping of non-ASCII characters to ASCII replacements
REPLACEMENTS = {
    # Smart quotes
    '\u2018': "'",  # Left single quote
    '\u2019': "'",  # Right single quote
    '\u201c': '"',  # Left double quote
    '\u201d': '"',  # Right double quote

    # Dashes
    '\u2014': '--',  # Em dash
    '\u2013': '-',   # En dash
    '\u00ad': '',    # Soft hyphen

    # Ellipsis
    '\u2026': '...',

    # Bullet points
    '\u2022': '*',
    '\u2023': '*',
    '\u2043': '-',
    '\u2219': '*',

    # Math symbols
    '\u00d7': 'x',   # Multiplication sign
    '\u00f7': '/',   # Division sign
    '\u00b1': '+-',  # Plus-minus
    '\u2264': '<=',  # Less than or equal
    '\u2265': '>=',  # Greater than or equal
    '\u2260': '!=',  # Not equal
    '\u00ac': 'NOT ', # Logical NOT

    # Copyright/Trademark
    '\u00a9': '(c)',
    '\u00ae': '(R)',
    '\u2122': '(TM)',

    # Degree symbol
    '\u00b0': ' degrees',

    # Fractions
    '\u00bc': '1/4',
    '\u00bd': '1/2',
    '\u00be': '3/4',
    '\u2150': '1/7',
    '\u2151': '1/9',
    '\u2152': '1/10',
    '\u2153': '1/3',
    '\u2154': '2/3',
    '\u2155': '1/5',
    '\u2156': '2/5',
    '\u2157': '3/5',
    '\u2158': '4/5',
    '\u2159': '1/6',
    '\u215a': '5/6',
    '\u215b': '1/8',
    '\u215c': '3/8',
    '\u215d': '5/8',
    '\u215e': '7/8',

    # Arrows
    '\u2190': '<-',
    '\u2191': '^',
    '\u2192': '->',
    '\u2193': 'v',
    '\u2194': '<->',
    '\u21d0': '<=',
    '\u21d2': '=>',
    '\u21d4': '<=>',

    # Check/X marks
    '\u2713': '[x]',  # Check mark
    '\u2714': '[x]',  # Heavy check mark
    '\u2717': '[ ]',  # Ballot X
    '\u2718': '[ ]',  # Heavy ballot X

    # Miscellaneous
    '\u00a0': ' ',    # Non-breaking space
    '\u00a9': '(c)',
    '\u2022': '*',
    '\u2027': '.',
    '\u2042': '***',
    '\u2043': '-',
    '\u2053': '~',
    '\u2060': '',     # Word joiner
    '\u2122': '(TM)',
    '\ufeff': '',     # BOM
}


def clean_text(text: str) -> str:
    """Replace all non-ASCII characters with ASCII equivalents."""
    result = text
    for char, replacement in REPLACEMENTS.items():
        result = result.replace(char, replacement)
    return result


def clean_file(input_path: Path, output_path: Path = None, in_place: bool = False) -> None:
    """Clean a file's contents."""
    text = input_path.read_text(encoding='utf-8')
    cleaned = clean_text(text)

    if in_place:
        output_path = input_path
    elif output_path is None:
        output_path = input_path.with_suffix(input_path.suffix + '.ascii')

    output_path.write_text(cleaned, encoding='utf-8')
    print(f"Cleaned: {input_path} -> {output_path}")


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Replace non-ASCII characters with ASCII equivalents.'
    )
    parser.add_argument(
        'files',
        nargs='*',
        help='Files to clean'
    )
    parser.add_argument(
        '-i', '--in-place',
        action='store_true',
        help='Modify files in place'
    )
    parser.add_argument(
        '-o', '--output',
        help='Output directory (for non-in-place mode)'
    )
    parser.add_argument(
        '-s', '--stdin',
        action='store_true',
        help='Read from stdin and write to stdout'
    )

    args = parser.parse_args()

    if args.stdin:
        import sys
        text = sys.stdin.read()
        print(clean_text(text), end='')
        return

    if not args.files:
        parser.print_help()
        return

    for file_path in args.files:
        input_path = Path(file_path)
        if not input_path.exists():
            print(f"Error: File not found: {input_path}")
            continue

        if args.output:
            output_path = Path(args.output) / input_path.name
        else:
            output_path = None

        clean_file(input_path, output_path, in_place=args.in_place)


if __name__ == '__main__':
    main()
